/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CCollectionIdIndexRouteImport } from './routes/c.$collectionId.index'
import { Route as CCollectionIdSplatRouteImport } from './routes/c.$collectionId.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CCollectionIdIndexRoute = CCollectionIdIndexRouteImport.update({
  id: '/c/$collectionId/',
  path: '/c/$collectionId/',
  getParentRoute: () => rootRouteImport,
} as any)
const CCollectionIdSplatRoute = CCollectionIdSplatRouteImport.update({
  id: '/c/$collectionId/$',
  path: '/c/$collectionId/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/c/$collectionId/$': typeof CCollectionIdSplatRoute
  '/c/$collectionId': typeof CCollectionIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/c/$collectionId/$': typeof CCollectionIdSplatRoute
  '/c/$collectionId': typeof CCollectionIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/c/$collectionId/$': typeof CCollectionIdSplatRoute
  '/c/$collectionId/': typeof CCollectionIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/c/$collectionId/$' | '/c/$collectionId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/c/$collectionId/$' | '/c/$collectionId'
  id: '__root__' | '/' | '/c/$collectionId/$' | '/c/$collectionId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CCollectionIdSplatRoute: typeof CCollectionIdSplatRoute
  CCollectionIdIndexRoute: typeof CCollectionIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$collectionId/': {
      id: '/c/$collectionId/'
      path: '/c/$collectionId'
      fullPath: '/c/$collectionId'
      preLoaderRoute: typeof CCollectionIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$collectionId/$': {
      id: '/c/$collectionId/$'
      path: '/c/$collectionId/$'
      fullPath: '/c/$collectionId/$'
      preLoaderRoute: typeof CCollectionIdSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CCollectionIdSplatRoute: CCollectionIdSplatRoute,
  CCollectionIdIndexRoute: CCollectionIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
